[build-system]
requires = ["setuptools>=51.0", "wheel>=0.36"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ["py38", "py39", "py310"]

[tool.isort]
profile = "black"
line_length = 120
