[build-system]
requires = ["setuptools>=51.0", "wheel>=0.36"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100
