# This file is automatically generated. Do not edit it.
from typing import Any

from gethash.script import gethashcli, script_main

META = {"command_name": "blake2s", "display_name": "BLAKE2s", "package": "hashlib", "hasher": "blake2s"}


@gethashcli(**META)
def main(files: tuple[str, ...], **kwargs: Any) -> None:
    """Generate or check BLAKE2s."""

    from hashlib import blake2s as H

    script_main(H(), files, **kwargs)


if __name__ == "__main__":
    main()
