# This file is automatically generated. Do not edit it.
from typing import Any

from gethash.script import gethashcli, script_main

META = {"command_name": "crc32", "display_name": "CRC32", "package": "gethash.wrappers.crc32", "hasher": "CRC32"}


@gethashcli(**META)
def main(files: tuple[str, ...], **kwargs: Any) -> None:
    """Generate or check CRC32."""

    from gethash.wrappers.crc32 import CRC32 as H

    script_main(H(), files, **kwargs)


if __name__ == "__main__":
    main()
