# This file is automatically generated. Do not edit it.
from typing import Any, Tuple

from gethash.script import gethashcli, script_main

META = {"command_name": "md4", "display_name": "MD4", "package": "Crypto.Hash.MD4", "hasher": "new"}


@gethashcli(**META)
def main(files: Tuple[str, ...], **kwargs: Any) -> None:
    """Generate or check MD4."""

    from Crypto.Hash.MD4 import new as H

    script_main(H(), files, **kwargs)


if __name__ == "__main__":
    main()
