# This file is automatically generated. Do not edit it.
from typing import Any, Tuple

from gethash.script import gethashcli, script_main

META = {"command_name": "md5", "display_name": "MD5", "package": "hashlib", "hasher": "md5"}


@gethashcli(**META)
def main(files: Tuple[str, ...], **kwargs: Any) -> None:
    """Generate or check MD5."""

    from hashlib import md5 as H

    script_main(H(), files, **kwargs)


if __name__ == "__main__":
    main()
