# This file is automatically generated. Do not edit it.
from typing import Any

from gethash.script import gethashcli, script_main

META = {"command_name": "sha256", "display_name": "SHA256", "package": "hashlib", "hasher": "sha256"}


@gethashcli(**META)
def main(files: tuple[str, ...], **kwargs: Any) -> None:
    """Generate or check SHA256."""

    from hashlib import sha256 as H

    script_main(H(), files, **kwargs)


if __name__ == "__main__":
    main()
